#!/usr/bin/env sh
LANG=zh_CN.UTF-8

export PATH=~/bin:~/.local/bin:$PATH

#export GTK_IM_MODULE=fcitx # Recommend not to set this
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

#export INPUT_METHOD=ibus
#export IMSETTINGS_MODULE=ibus
#export GTK_IM_MODULE=wayland
#export XMODIFIERS=@im=ibus
#export QT_IM_MODULES=wayland,ibus
#export QT_IM_MODULE=ibus
#export XIM_PROGRAM=ibus
#export SDL_IM_MODULE=ibus
#export GLFW_IM_MODULE=ibus

export QT_QPA_PLATFORMTHEME='qt5ct'

export XDG_MENU_PREFIX='arch-'

export TEXMFHOME='~/texmf'

export FZF_DEFAULT_COMMAND='fd --no-follow'

export UV_DEFAULT_INDEX='https://mirrors.zju.edu.cn/pypi/web/simple'
export RUSTUP_DIST_SERVER='https://mirrors.ustc.edu.cn/rust-static'
export RUSTUP_UPDATE_ROOT='https://mirrors.ustc.edu.cn/rust-static/rustup'

alias less='less -R'
alias vi='vim'

